sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "node"
before_install:
  - npm i -g npm@^6.13.4
before_script:
  - npm prune
after_success:
  - "curl -Lo travis_after_all.py https://git.io/travis_after_all"
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
